from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal


class User(AbstractUser):
    """
    Custom User model extending Django's AbstractUser.
    Adds a role field to differentiate user types.
    """
    ROLE_CHOICES = [
        ('PM', 'Project Manager'),
        ('FINANCE', 'Finance'),
        ('DEV', 'Developer'),
    ]
    
    role = models.CharField(
        max_length=10,
        choices=ROLE_CHOICES,
        default='DEV',
        help_text="User's role in the organization"
    )
    
    class Meta:
        db_table = 'users'
        ordering = ['username']
    
    def __str__(self):
        return f"{self.username} ({self.get_role_display()})"


class Project(models.Model):
    """
    Represents an Agile project.
    Contains basic project information and tracks creation time.
    """
    name = models.CharField(
        max_length=255,
        unique=True,
        help_text="Project name"
    )
    description = models.TextField(
        blank=True,
        help_text="Detailed project description"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when project was created"
    )
    
    class Meta:
        db_table = 'projects'
        ordering = ['-created_at']
    
    def __str__(self):
        return self.name


class Sprint(models.Model):
    """
    Represents a sprint within a project.
    Linked to a project via ForeignKey with cascade deletion.
    """
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='sprints',
        help_text="Project this sprint belongs to"
    )
    start_date = models.DateField(
        help_text="Sprint start date"
    )
    end_date = models.DateField(
        help_text="Sprint end date"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when sprint was created"
    )
    
    class Meta:
        db_table = 'sprints'
        ordering = ['-start_date']
        constraints = [
            models.CheckConstraint(
                check=models.Q(end_date__gte=models.F('start_date')),
                name='sprint_end_after_start'
            )
        ]
    
    def __str__(self):
        return f"{self.project.name} - Sprint {self.start_date} to {self.end_date}"


class SprintMetric(models.Model):
    """
    Financial and performance metrics for a sprint.
    One-to-one relationship with Sprint (each sprint has one metric set).
    """
    sprint = models.OneToOneField(
        Sprint,
        on_delete=models.CASCADE,
        related_name='metrics',
        primary_key=True,
        help_text="Sprint these metrics belong to"
    )
    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        help_text="Total cost of the sprint"
    )
    estimated_business_value = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        help_text="Estimated business value generated by sprint"
    )
    velocity = models.IntegerField(
        validators=[MinValueValidator(0)],
        help_text="Sprint velocity (story points completed)"
    )
    
    class Meta:
        db_table = 'sprint_metrics'
    
    @property
    def roi(self):
        """
        Calculate Return on Investment (ROI).
        Formula: (Estimated Value - Cost) / Cost
        Returns None if cost is zero to avoid division by zero.
        """
        if self.cost == 0:
            return None
        return float((self.estimated_business_value - self.cost) / self.cost)
    
    def __str__(self):
        return f"Metrics for {self.sprint}"