# Generated by Django 4.2.7 on 2025-11-10 03:22

from decimal import Decimal
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed project description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when project was created')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Sprint start date')),
                ('end_date', models.DateField(help_text='Sprint end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when sprint was created')),
                ('project', models.ForeignKey(help_text='Project this sprint belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='app.project')),
            ],
            options={
                'db_table': 'sprints',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SprintMetric',
            fields=[
                ('sprint', models.OneToOneField(help_text='Sprint these metrics belong to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='app.sprint')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total cost of the sprint', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_business_value', models.DecimalField(decimal_places=2, help_text='Estimated business value generated by sprint', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('velocity', models.IntegerField(help_text='Sprint velocity (story points completed)', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'sprint_metrics',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('PM', 'Project Manager'), ('FINANCE', 'Finance'), ('DEV', 'Developer')], default='DEV', help_text="User's role in the organization", max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='sprint_end_after_start'),
        ),
    ]
